name: OpenOCD CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Install basic build tools and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libtool \
          pkg-config \
          libjim0.79 \
          libjim-dev \
          autoconf \
          automake \
          texinfo \
          libusb-1.0-0-dev
        
    - name: Install optional dependencies
      run: |
        sudo apt-get install -y \
          libftdi1-dev \
          libhidapi-dev \
          libgpiod-dev \
          libjaylink-dev \
          libcapstone-dev
        
    - name: Set up ${{ matrix.compiler }}
      if: matrix.compiler == 'clang'
      run: |
        sudo apt-get install -y clang
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        
    - name: Configure with ${{ matrix.compiler }}
      run: |
        ./bootstrap
        ./configure
        
    - name: Build with ${{ matrix.compiler }}
      run: |
        make -j$(nproc)
        
    - name: Run tests
      run: |
        make check
        
    - name: Run distcheck
      run: |
        make distcheck
        
  checkpatch:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install checkpatch dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          perl \
          python3 \
          python3-ply
          
    - name: Run checkpatch
      run: |
        ./contrib/checkpatch.pl --file *.c
